#!/usr/bin/env bash
#
# A wizard walks a human through a manual procedure, step by step.
# Generated by the /wizard skill.
#
# Everything above the "STAGES" marker is the wizard library: do not hand-edit
# it. Author the per-step stages below the marker.

set -euo pipefail

# ──────────────────────────────────────────────────────────────────────────
# Wizard library: delightful, consistent UX, identical across every wizard.
# ──────────────────────────────────────────────────────────────────────────

if [[ -t 1 ]] && command -v tput >/dev/null 2>&1 && [[ "$(tput colors 2>/dev/null || echo 0)" -ge 8 ]]; then
  BOLD=$(tput bold); DIM=$(tput dim); RESET=$(tput sgr0)
  BLUE=$(tput setaf 4); GREEN=$(tput setaf 2); YELLOW=$(tput setaf 3); RED=$(tput setaf 1)
else
  BOLD=""; DIM=""; RESET=""; BLUE=""; GREEN=""; YELLOW=""; RED=""
fi

# Author sets this at the top of the stages section.
TOTAL_STAGES=0

_STAGE_INDEX=0
ENV_FILE="${ENV_FILE:-.env}"
WRITTEN_ENV=()    # KEYs written to ENV_FILE this run
WRITTEN_SECRET=() # secret NAMEs set this run
SKIPPED=()        # things we couldn't do (e.g. gh missing)

# _clear wipes the terminal so only the current step is on screen. No-op when
# output isn't a terminal, so piped logs stay readable.
_clear() {
  [[ -t 1 ]] || return 0
  if command -v tput >/dev/null 2>&1; then tput clear; else printf '\033[2J\033[3J\033[H'; fi
}

# banner "Title" shows the opening frame: what this wizard does.
banner() {
  _clear
  printf '\n%s%s  %s%s\n' "$BOLD" "$BLUE" "$1" "$RESET"
  printf '%s  %s stages%s\n\n' "$DIM" "$TOTAL_STAGES" "$RESET"
  printf '%s  You drive the browser; this wizard tells you exactly what to do and\n' "$DIM"
  printf '  captures the values you copy back. Stop any time with Ctrl-C and re-run\n'
  printf '  later, since it remembers values already saved.%s\n' "$RESET"
  pause "Ready to start?"
}

# stage "Name" clears the screen, then announces a stage and shows progress.
# Clearing keeps only the current step on screen.
stage() {
  _clear
  _STAGE_INDEX=$((_STAGE_INDEX + 1))
  printf '\n%s%s▸ Stage %s/%s · %s%s\n' \
    "$BOLD" "$BLUE" "$_STAGE_INDEX" "$TOTAL_STAGES" "$1" "$RESET"
}

# say "..." prints a plain instruction line.
say()  { printf '  %s\n' "$1"; }
# step "..." is a numbered-feeling action the human takes in the browser.
step() { printf '  %s•%s %s\n' "$BLUE" "$RESET" "$1"; }
note() { printf '  %s%s%s\n' "$DIM" "$1" "$RESET"; }
warn() { printf '  %s⚠ %s%s\n' "$YELLOW" "$1" "$RESET"; }

# open_url URL opens it in the human's browser, cross-platform incl. WSL.
open_url() {
  local url="$1"
  printf '  %s↗ opening%s %s\n' "$GREEN" "$RESET" "$url"
  { if   command -v wslview     >/dev/null 2>&1; then wslview "$url"
    elif command -v explorer.exe >/dev/null 2>&1; then explorer.exe "$url"
    elif command -v xdg-open    >/dev/null 2>&1; then xdg-open "$url"
    elif command -v open        >/dev/null 2>&1; then open "$url"
    else warn "couldn't open a browser; visit it manually: $url"; fi
  } >/dev/null 2>&1 || warn "couldn't open a browser, so visit it manually: $url"
}

# pause "msg" waits for the human to confirm they've done the manual part.
pause() {
  printf '  %s%s%s ' "$DIM" "${1:-Press Enter to continue}" "$RESET"
  read -r _ || true
}

# confirm "question" is a y/N gate; returns success on yes.
confirm() {
  local reply=""
  printf '  %s? %s [y/N] ' "$YELLOW" "$1"
  read -r reply || true
  [[ "$reply" =~ ^[Yy] ]]
}

# _existing KEY: current value of KEY in ENV_FILE, if any.
_existing() {
  [[ -f "$ENV_FILE" ]] || return 1
  local line; line=$(grep -E "^${1}=" "$ENV_FILE" | tail -n1) || return 1
  printf '%s' "${line#*=}"
}

# ask KEY "Prompt" reads a value into $KEY. Offers the existing .env value as
# a default on re-runs (Enter keeps it). Visible input (non-secret).
ask() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -r input || true
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# ask_secret KEY "Prompt" is like ask, but input is hidden.
ask_secret() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -rs input || true
  printf '\n'
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# write_env KEY VALUE upserts KEY=VALUE into ENV_FILE (creates it; replaces
# any existing line). Idempotent.
write_env() {
  local key="$1" value="$2" tmp
  touch "$ENV_FILE"
  tmp=$(mktemp)
  grep -vE "^${key}=" "$ENV_FILE" > "$tmp" || true
  printf '%s=%s\n' "$key" "$value" >> "$tmp"
  mv "$tmp" "$ENV_FILE"
  WRITTEN_ENV+=("$key")
  printf '  %s✓ wrote%s %s → %s\n' "$GREEN" "$RESET" "$key" "$ENV_FILE"
}

# set_secret NAME VALUE sets a GitHub Actions repo secret via gh. Falls back
# to a warning (and records it) if gh is unavailable or unauthenticated.
set_secret() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if printf '%s' "$value" | gh secret set "$name" >/dev/null 2>&1; then
      WRITTEN_SECRET+=("$name")
      printf '  %s✓ set%s GitHub secret %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub secret $name (set it manually: gh secret set $name)")
  warn "skipped GitHub secret $name: gh not ready; set it later"
}

# set_var NAME VALUE sets a GitHub Actions repo variable (non-secret).
set_var() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if gh variable set "$name" --body "$value" >/dev/null 2>&1; then
      printf '  %s✓ set%s GitHub variable %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub variable $name")
  warn "skipped GitHub variable $name, gh not ready; set it later"
}

# finish clears, then shows a closing summary of everything configured.
finish() {
  _clear
  printf '\n%s%s  ✓ Setup complete%s\n' "$BOLD" "$GREEN" "$RESET"
  (( ${#WRITTEN_ENV[@]} ))    && note "wrote ${#WRITTEN_ENV[@]} value(s) to $ENV_FILE: ${WRITTEN_ENV[*]}"
  (( ${#WRITTEN_SECRET[@]} )) && note "set ${#WRITTEN_SECRET[@]} GitHub secret(s): ${WRITTEN_SECRET[*]}"
  if (( ${#SKIPPED[@]} )); then
    printf '\n'; warn "still to do by hand:"
    for s in "${SKIPPED[@]}"; do note "  - $s"; done
  fi
  printf '\n'
}

# ──────────────────────────────────────────────────────────────────────────
# STAGES: author this section. One stage() per step the human takes.
# Replace the example below. Set TOTAL_STAGES to match the stages you write.
# ──────────────────────────────────────────────────────────────────────────
#
# Connects wit03.xyz to the Vault (docs/adr/0001, docs/vault/README.md). Run from the repo root:
#   bash scripts/setup-vault.sh

TOTAL_STAGES=6

VAULT_REPO="wit03/projects-vault"
VERCEL_PROJECT="https://vercel.com/jarukit-jintanasathirakuls-projects/wit03-xyz"
TEMPLATE_DIR="$(cd "$(dirname "$0")/.." && pwd)/docs/vault/template"

gh_ready() { command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; }

banner "Connect wit03.xyz to the Projects Vault"

# ── 1 ─────────────────────────────────────────────────────────────────────
stage "Create the private Vault repo"
say "The Vault is a private repo, $VAULT_REPO, seeded from docs/vault/template:"
note "an example note (unpublished), a .gitignore, and the Action that redeploys the site."
if gh_ready && gh repo view "$VAULT_REPO" >/dev/null 2>&1; then
  say "$VAULT_REPO already exists. Skipping."
elif confirm "Create $VAULT_REPO (private) and push the template?"; then
  tmp=$(mktemp -d)
  cp -R "$TEMPLATE_DIR"/. "$tmp"/
  git -C "$tmp" init -q -b main
  git -C "$tmp" add -A
  git -C "$tmp" -c user.name="$(git config user.name || echo wit03)" -c user.email="$(git config user.email || echo noreply@wit03.xyz)" \
    commit -q -m "Start the Projects Vault"
  if gh_ready; then
    gh repo create "$VAULT_REPO" --private --source "$tmp" --push >/dev/null
    printf '  %s✓ created%s %s and pushed the template\n' "$GREEN" "$RESET" "$VAULT_REPO"
  else
    open_url "https://github.com/new"
    step "Owner: wit03. Repository name: projects-vault."
    step "Choose Private. Leave README, .gitignore and license unticked. Create repository."
    pause "Press Enter once the empty repo exists"
    git -C "$tmp" remote add origin "https://github.com/$VAULT_REPO.git"
    git -C "$tmp" push -q -u origin main
    printf '  %s✓ pushed%s the template to %s\n' "$GREEN" "$RESET" "$VAULT_REPO"
  fi
  rm -rf "$tmp"
else
  SKIPPED+=("Create $VAULT_REPO from docs/vault/template")
fi
pause

# ── 2 ─────────────────────────────────────────────────────────────────────
stage "A read-only token for the site's builds"
say "Vercel needs to read the Vault at build time. Make a token that can only do that."
open_url "https://github.com/settings/personal-access-tokens/new"
step "Token name: wit03.xyz build: read Vault. Expiration: 1 year (set yourself a reminder)."
step "Resource owner: wit03. Repository access: Only select repositories → projects-vault."
step "Permissions → Repository permissions → Contents: Read-only. Leave everything else as it is."
step "Generate token, then copy it (starts with github_pat_)."
ask_secret VAULT_TOKEN "Paste the token:"
note "Not saved locally: it only goes into Vercel in the next stage."
pause

# ── 3 ─────────────────────────────────────────────────────────────────────
stage "Give the token to Vercel"
open_url "$VERCEL_PROJECT/settings/environment-variables"
step "Key: VAULT_TOKEN"
step "Value: paste the token below into the Value field."
step "Environments: Production and Preview. Turn on Sensitive. Save."
if [[ -n "${VAULT_TOKEN:-}" ]]; then
  if command -v pbcopy >/dev/null 2>&1; then printf '%s' "$VAULT_TOKEN" | pbcopy && note "(copied to your clipboard)"
  elif command -v wl-copy >/dev/null 2>&1; then printf '%s' "$VAULT_TOKEN" | wl-copy && note "(copied to your clipboard)"
  elif command -v xclip >/dev/null 2>&1; then printf '%s' "$VAULT_TOKEN" | xclip -selection clipboard && note "(copied to your clipboard)"
  else note "Paste the token you copied in the last stage."; fi
fi
pause "Press Enter once VAULT_TOKEN is saved in Vercel"

# ── 4 ─────────────────────────────────────────────────────────────────────
stage "Redeploy the site when the Vault changes"
open_url "$VERCEL_PROJECT/settings/git"
step "Scroll to Deploy Hooks. Name: projects-vault. Branch: master. Create Hook."
step "Copy the hook URL (https://api.vercel.com/v1/integrations/deploy/…)."
ask_secret VERCEL_DEPLOY_HOOK "Paste the deploy hook URL:"
if gh_ready && printf '%s' "$VERCEL_DEPLOY_HOOK" | gh secret set VERCEL_DEPLOY_HOOK --repo "$VAULT_REPO" >/dev/null 2>&1; then
  WRITTEN_SECRET+=("VERCEL_DEPLOY_HOOK ($VAULT_REPO)")
  printf '  %s✓ set%s VERCEL_DEPLOY_HOOK on %s\n' "$GREEN" "$RESET" "$VAULT_REPO"
else
  open_url "https://github.com/$VAULT_REPO/settings/secrets/actions/new"
  step "Name: VERCEL_DEPLOY_HOOK. Secret: the hook URL. Add secret."
  pause "Press Enter once the secret is added"
fi
pause

# ── 5 ─────────────────────────────────────────────────────────────────────
stage "Write in Obsidian"
say "Clone the Vault somewhere you keep notes, open it in Obsidian, and let it push for you."
step "git clone https://github.com/$VAULT_REPO.git ~/Obsidian/projects-vault (or anywhere you like)"
step "Obsidian → Open folder as vault → pick that folder."
step "Settings → Community plugins → Browse → search \"Git\" (by Vinzent) → Install → Enable."
step "Git plugin settings: set an auto commit-and-sync interval (e.g. 10 minutes)."
ask VAULT_PATH "Where did you clone it? (full path, for local previews):"
if [[ -n "${VAULT_PATH:-}" ]]; then
  write_env VAULT_PATH "${VAULT_PATH/#\~/$HOME}"
  note "pnpm dev now reads your Vault, so edits show up on refresh."
fi
pause

# ── 6 ─────────────────────────────────────────────────────────────────────
stage "First publish"
say "Try it end to end:"
step "In Obsidian, open Projects/Example project.md, set publish: true (or write your own note)."
step "Commit and sync (Git plugin: Ctrl/Cmd-P → \"Git: Commit-and-sync\")."
step "Watch the Action run, then the Vercel deploy:"
open_url "https://github.com/$VAULT_REPO/actions"
note "A broken note fails the build and the live site keeps its last good version;"
note "the Vercel build log names the note and the field to fix."
pause "Press Enter when you've seen it live (or to finish now)"

finish
